{
 "title": "AI Arena Clients",
 "description": "CPU and RAM usage of AI Arena Clients",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "1m" }
  ]
 },
 "panels": [
  {
   "title": "Match results",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (status) (\r\n  label_replace(\r\n    label_replace(\r\n      label_replace(\r\n        label_replace(\r\n          label_replace(\r\n            count_over_time(\r\n              {namespace=\"arenaclients\"} \r\n              |~ \"Match result: AiArenaGameResult\" \r\n              | regexp `, result: (?P<result>\\w+)`\r\n              [$__range]\r\n            ),\r\n            \"status\", \"Game Rules\", \"result\", \"Player1Win|Player2Win|Tie\"\r\n          ),\r\n          \"status\", \"Bot Crash\", \"result\", \"Player1Crash|Player2Crash\"\r\n        ),\r\n        \"status\", \"Bot Timeout\", \"result\", \"Player1TimeOut|Player2TimeOut\"\r\n      ),\r\n      \"status\", \"Error\", \"result\", \"Error\"\r\n    ),\r\n    \"status\", \"Initialization Error\", \"result\", \"InitializationError\"\r\n  )\r\n)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Failed matches",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "{namespace=\"arenaclients\"} \r\n|~ \"Match result: AiArenaGameResult\"\r\n| regexp `match_id: (?P<match_id>\\d+),.*result: (?P<result>\\w+), game_steps: (?P<game_steps>\\d+)`\r\n| result !~ \"Player1Win|Player2Win|Tie\""
    }
   ]
  },
  {
   "title": "Last empty match schedule",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 16, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "{namespace=\"arenaclients\", container=\"k8s-controller\"} |~ \"No game available for client.\" ",
     "maxLines": 1
    }
   ]
  },
  {
   "title": "Last errors",
   "type": "logs",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 2 },
   "targets": [
    {
     "expr": "{namespace=\"arenaclients\"} |= \"ERROR\"",
     "maxLines": 50
    }
   ]
  },
  {
   "title": "CPU utilization",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\r\n  rate(\r\n    container_cpu_usage_seconds_total{\r\n      container_label_io_kubernetes_pod_namespace=\"arenaclients\",\r\n      container_label_io_kubernetes_container_name=~\"game-controller|bot-controller-1|bot-controller-2|match_controller\"\r\n    }[$__range]\r\n  )\r\n)",
     "legendFormat": "Matches"
    },
    { "expression": "$Used - $Matches", "type": "math" },
    { "expression": "$Cores - $Used", "type": "math" }
   ]
  },
  {
   "title": "CPU (component)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 8 },
   "targets": [
    {
     "expr": "sum by (container_label_io_kubernetes_container_name)(\r\n    rate(\r\n        container_cpu_usage_seconds_total{\r\n            container_label_io_kubernetes_pod_namespace=\"arenaclients\",\r\n            container_label_io_kubernetes_container_name=~\"game-controller|bot-controller-1|bot-controller-2|match_controller\"\r\n        }\r\n        [1m]\r\n    )\r\n)",
     "legendFormat": "{{container_label_io_kubernetes_container_name}}"
    }
   ]
  },
  {
   "title": "CPU (namespace)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_usage_seconds_total{name=~\".+\"}[1m])) by (container_label_io_kubernetes_pod_namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bps" } },
   "targets": [
    {
     "expr": "sum by (instance) (rate(node_network_receive_bytes_total{device!~\"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*\"}[1m])) * 8",
     "legendFormat": "Inbound {{instance}}"
    },
    {
     "expr": "sum by (instance) (rate(node_network_transmit_bytes_total{device!~\"lo|veth.*|docker.*|flannel.*|cali.*|cbr.*\"}[1m])) * 8",
     "legendFormat": "Outbound {{instance}}"
    }
   ]
  },
  {
   "title": "RAM (component)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (container_label_io_kubernetes_container_name)(\r\n    container_memory_rss{\r\n        container_label_io_kubernetes_pod_namespace=\"arenaclients\",\r\n        container_label_io_kubernetes_container_name=~\"game-controller|bot-controller-1|bot-controller-2|match_controller\"\r\n    }\r\n)",
     "legendFormat": "{{container_label_io_kubernetes_container_name}}"
    }
   ]
  },
  {
   "title": "RAM (namespace)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 10, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_memory_rss{name=~\".+\"}) by (container_label_io_kubernetes_pod_namespace)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Available disk space",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "sum by (instance) (\r\n  node_filesystem_avail_bytes{fstype!~\"tmpfs|ramfs|autofs|vfat|overlay\", mountpoint=\"/\"}\r\n) / 1024 / 1024 / 1024",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "GraphQL errors",
   "type": "logs",
   "gridPos": { "h": 3, "w": 20, "x": 4, "y": 22 },
   "targets": [
    {
     "expr": "{namespace=\"arenaclients\"} |= \"Failed to submit result via GraphQL\"",
     "maxLines": 50
    }
   ]
  }
 ]
}